version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    image: front:0.0.1
    ports:
      - "8083:80"
    restart: always
    networks:
      mongo-network:
        aliases:
          - mongo-host
networks:
  mongo-network:
    name: mongo_net
    driver: bridge
